# Generated by Django 4.2.9 on 2024-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.IntegerField()),
                ('f2', models.CharField(max_length=100)),
                ('f3', models.FloatField()),
                ('f4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.IntegerField()),
                ('f2', models.CharField(max_length=100)),
                ('f3', models.FloatField()),
                ('f4', models.FloatField()),
            ],
        ),
    ]
